name: makers
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../volumes/mysql:/var/lib/mysql
      
  web:
    build: 
      context: .
      dockerfile: Dockerfile 

    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://mysql:${MYSQL_USER}@${MYSQL_PASSWORD}/${MYSQL_DATABASE}
    depends_on:
      - db